import type { Classification } from './analysis'

export const CLASSIFICATION_META: Record<
  Classification,
  { label: string; glyph: string; color: string; description: string; phrase: string }
> = {
  brilliant: { phrase: 'é brilhante',
    label: 'Brilhante',
    glyph: '!!',
    color: '#26b5aa',
    description: 'Um sacrifício correto que só um olhar atento encontra.',
  },
  great: { phrase: 'é um ótimo lance',
    label: 'Ótimo',
    glyph: '!',
    color: '#5c8fd9',
    description: 'O único lance bom da posição.',
  },
  best: { phrase: 'é o melhor lance', label: 'Melhor', glyph: '★', color: '#86b83e', description: 'O lance escolhido pelo motor.' },
  excellent: { phrase: 'é excelente',
    label: 'Excelente',
    glyph: '✓✓',
    color: '#a3c45a',
    description: 'Quase tão bom quanto o melhor.',
  },
  good: { phrase: 'é um bom lance', label: 'Bom', glyph: '✓', color: '#8fa98c', description: 'Um lance sólido, sem grandes perdas.' },
  book: { phrase: 'é teoria', label: 'Teoria', glyph: 'T', color: '#b38b5d', description: 'Lance conhecido da teoria de aberturas.' },
  inaccuracy: { phrase: 'é uma imprecisão',
    label: 'Imprecisão',
    glyph: '?!',
    color: '#e9be3f',
    description: 'Havia um lance claramente melhor.',
  },
  mistake: { phrase: 'é um erro', label: 'Erro', glyph: '?', color: '#e8893a', description: 'Um lance que piora bastante a posição.' },
  miss: { phrase: 'é uma chance perdida',
    label: 'Chance perdida',
    glyph: '✕',
    color: '#e0656b',
    description: 'O adversário deu uma chance e ela passou.',
  },
  blunder: { phrase: 'é uma capivarada',
    label: 'Capivarada',
    glyph: '??',
    color: '#d9463c',
    description: 'Um erro grave, que muda o rumo da partida.',
  },
}
